### PR TITLE
Add `Field Guide for Tech + Product`

### PR DESCRIPTION
**Pull request by davisshaver**
This pull request will add a `Field Guide for Tech + Product` that is meant to help address a couple issues I see:
- Oftentimes our work appears arcane even to journalists and other colleagues within our own organizations. This feeling of mystery inhibits collaboration, and reduces cross-pollination of talent & ideas from one division to another.
- A lot of students I meet seem unaware that there are "news" opportunities outside of being a journalist/reporter. This lack of knowledge can either cause students to not take the courses/invest in the skills that would be relevant for this line of work while in college, or even worse, attrition out of the industry because they hear that it's low-paying and "doomed".

### CODE REVIEW

**Comment by davisshaver** [comment]
One philosophical question for the field guide: How to address the distinction between Tech + Product and Interactive News/Journo-Programmers. News Nerdery has a good mix of both right now. Maybe we should have two field guides?

**Comment by danielbachhuber** [comment]
> distinction between Tech + Product

This distinction is actually fascinating to me. I'm really curious as to how everyone views themselves within their organizations, and what the relative strengths are to each approach.

**Comment by davisshaver** [comment]
Just caught up with @jueyang on Slack. She's going to make a PR this week starting with Git/Github, and then possibly Agile, Lean, and Jobs-to-be-Done. :stars:

**Comment by davisshaver** [comment]
I'm going to tackle Trello, OmniGraffle/balsmiq, Text Editors, and IDE's this week.

Then, after we have @jueyang's PR merged, we'd just need Python and Swift to finish off a first version of this... any takers?

**Comment by myersjustinc** [comment]
Can't help with Swift, but I can take a stab at Python (and add Ruby for good measure). If I don't get to it sooner, I definitely can do this while I'm on a plane to ONA in a week.

**Comment by jueyang** [comment]
Apologies for the lag. My PR is coming this week!

**Comment by davisshaver** [comment]
Added descriptions for Trello, Text Editors, OmniGraffle/Balsmiq, and IDE's.

Still need:
- [ ] Jobs to be done
- [ ] Lean
- [ ] Python
- [ ] Swift
- [ ] Git/Github

@jueyang and @myersjustinc have graciously offered to cover some of these. I'm budgeting time for next Monday to wrap up whatever's left and then :ship: this doc.

**Pull request merged**
