### PR TITLE
Update slack.md

### PR DESCRIPTION
**Pull request by davisshaver**

### CODE REVIEW

**Comment by davisshaver** [comment]
@danielbachhuber  @newsnerdery/mods  what should we use `#announcements` for? Locked down and default channel for network announcements? Or self-promo announcements from people/orgs?

**Comment by danielbachhuber** [comment]
> what should we use #announcements for? Locked down and default channel for network announcements?

It would be nice if we could use it in a similar manner to WordPress Slack. I'm not sure how that's configured though.

**Comment by davisshaver** [comment]
@danielbachhuber WordPress.org has a partnership with Slack for access to higher grade features. There's a [general offer to nonprofits for free Standard plan](https://slack.zendesk.com/hc/en-us/articles/204368833-Slack-for-Nonprofits), which would get us more features, but I'm not sure we qualify at this point.

**Comment by danielbachhuber** [comment]
> WordPress.org has a partnership with Slack for access to higher grade features.

:( I think maybe we should punt on `#announcements` for now then. We can just `@channel` in `#watercooler`

**Comment by davisshaver** [comment]
Sounds like a plan. Updated. Merge?

**Comment by danielbachhuber** [comment]
:cherries:

**Pull request merged**
